"""initial schema

Revision ID: 2b10d103d2d4
Revises: 
Create Date: 2026-05-04 17:54:48.557350

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2b10d103d2d4'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('restaurants',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('google_place_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('city', sa.String(), nullable=False),
    sa.Column('neighborhood', sa.String(), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lng', sa.Float(), nullable=True),
    sa.Column('price_tier', sa.Integer(), nullable=True),
    sa.Column('google_rating', sa.Float(), nullable=True),
    sa.Column('google_review_count', sa.Integer(), nullable=True),
    sa.Column('website', sa.Text(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('google_place_id')
    )
    with op.batch_alter_table('restaurants', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_restaurants_city'), ['city'], unique=False)
        batch_op.create_index(batch_op.f('ix_restaurants_slug'), ['slug'], unique=True)

    op.create_table('reviews',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('restaurant_id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('source_id', sa.String(), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('author', sa.String(), nullable=True),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('rating', sa.Float(), nullable=True),
    sa.Column('reddit_score', sa.Integer(), nullable=True),
    sa.Column('posted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ingested_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source', 'source_id', name='uq_reviews_source_source_id')
    )
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reviews_restaurant_id'), ['restaurant_id'], unique=False)

    op.create_table('scores',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('restaurant_id', sa.Integer(), nullable=False),
    sa.Column('quality_score', sa.Float(), nullable=True),
    sa.Column('service_score', sa.Float(), nullable=True),
    sa.Column('ambiance_score', sa.Float(), nullable=True),
    sa.Column('prime_score', sa.Float(), nullable=True),
    sa.Column('google_review_count_used', sa.Integer(), nullable=True),
    sa.Column('reddit_mention_count_used', sa.Integer(), nullable=True),
    sa.Column('date_range_start', sa.Date(), nullable=True),
    sa.Column('date_range_end', sa.Date(), nullable=True),
    sa.Column('house_take', sa.Text(), nullable=True),
    sa.Column('quality_themes_pos', sa.JSON(), nullable=True),
    sa.Column('quality_themes_neg', sa.JSON(), nullable=True),
    sa.Column('service_themes_pos', sa.JSON(), nullable=True),
    sa.Column('service_themes_neg', sa.JSON(), nullable=True),
    sa.Column('ambiance_themes_pos', sa.JSON(), nullable=True),
    sa.Column('ambiance_themes_neg', sa.JSON(), nullable=True),
    sa.Column('summary_generated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('computed_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('scores', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_scores_computed_at'), ['computed_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_scores_restaurant_id'), ['restaurant_id'], unique=False)

    op.create_table('sentences',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('review_id', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('pillar', sa.String(), nullable=False),
    sa.Column('sentiment', sa.Float(), nullable=False),
    sa.Column('classifier_version', sa.String(), nullable=False),
    sa.Column('classified_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['review_id'], ['reviews.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sentences', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sentences_pillar'), ['pillar'], unique=False)
        batch_op.create_index(batch_op.f('ix_sentences_review_id'), ['review_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sentences', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sentences_review_id'))
        batch_op.drop_index(batch_op.f('ix_sentences_pillar'))

    op.drop_table('sentences')
    with op.batch_alter_table('scores', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_scores_restaurant_id'))
        batch_op.drop_index(batch_op.f('ix_scores_computed_at'))

    op.drop_table('scores')
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reviews_restaurant_id'))

    op.drop_table('reviews')
    with op.batch_alter_table('restaurants', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_restaurants_slug'))
        batch_op.drop_index(batch_op.f('ix_restaurants_city'))

    op.drop_table('restaurants')
    # ### end Alembic commands ###
