"""add volume-aware shrinkage debug fields

Revision ID: 57a246a4ca47
Revises: 8c5ec70d47b9
Create Date: 2026-05-04 21:30:55.127027

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '57a246a4ca47'
down_revision: Union[str, None] = '8c5ec70d47b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scores', schema=None) as batch_op:
        batch_op.add_column(sa.Column('effective_k', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('confidence_factor', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scores', schema=None) as batch_op:
        batch_op.drop_column('confidence_factor')
        batch_op.drop_column('effective_k')

    # ### end Alembic commands ###
