"""add shrinkage raw scores n_sentences and google_review_count snapshot

Revision ID: 8c5ec70d47b9
Revises: 2b10d103d2d4
Create Date: 2026-05-04 21:23:24.784077

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8c5ec70d47b9'
down_revision: Union[str, None] = '2b10d103d2d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scores', schema=None) as batch_op:
        batch_op.add_column(sa.Column('raw_quality_score', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('raw_service_score', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('raw_ambiance_score', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('quality_n_sentences', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('service_n_sentences', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('ambiance_n_sentences', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('google_review_count', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scores', schema=None) as batch_op:
        batch_op.drop_column('google_review_count')
        batch_op.drop_column('ambiance_n_sentences')
        batch_op.drop_column('service_n_sentences')
        batch_op.drop_column('quality_n_sentences')
        batch_op.drop_column('raw_ambiance_score')
        batch_op.drop_column('raw_service_score')
        batch_op.drop_column('raw_quality_score')

    # ### end Alembic commands ###
